# Selenium Hub, which parcels out browsers to test runners
hub:
  image: 'selenium/hub:2.45.0'
  expose:
    - 4444
# Firefox image with VNC on port 5950
firefox:
  image: "selenium/node-firefox-debug:2.45.0"
  ports:
    - "5950:5900"
  links:
    - hub
# Chrome image with VNC on port 5960
chrome:
  image: "selenium/node-chrome-debug:2.45.0"
  ports:
    - "5960:5900"
  links:
    - hub
# Jenkins slave.  SSH endpoint with some CLI tools installed
slave:
  build: 'slave'
  expose:
    - 22
  links:
    - hub
# The Jenkins server.  See README for details on SSH certs for talking to the slave
jenkins:
  image: 'jenkins:1.596.2'
  ports:
    - 8080:8080
  volumes:
    - ~/jenkins_home:/var/jenkins_home
  links:
    - slave
